name: mdp-classwork-1
on: push
jobs:
  Clone-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v3
        with:
          name: source-code
          path: .

  Build-container:
    runs-on: ubuntu-latest
    needs: Clone-repo
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .
      - run: docker build -t syndamia/mdp-classwork-1:latest .
      - run: docker save -o mdp-classwork-1_image.tar syndamia/mdp-classwork-1:latest
      - uses: actions/upload-artifact@v3
        with:
          name: built-image
          path: ./mdp-classwork-1_image.tar

  Push-container:
    runs-on: ubuntu-latest
    needs: Build-container
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: built-image
          path: .
      - run: docker load -i ./mdp-classwork-1_image.tar
      - env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u syndamia -p "$DOCKERHUB_PASSWORD"
      - run: docker tag syndamia/mdp-classwork-1:latest syndamia/mdp-classwork-1:latest
      - run: docker push syndamia/mdp-classwork-1:latest
