name: mdp-classwork-1
on: push
jobs:
  Clone-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v3
        with:
          name: source-code
          path: .

  Build-image:
    runs-on: ubuntu-latest
    needs: Clone-repo
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .
      - name: Build Docker image
        run: docker build -t syndamia/mdp-classwork-1:latest .
      - name: Store Docker image into tar archive
        run: docker save -o mdp-classwork-1_image.tar syndamia/mdp-classwork-1:latest
      - uses: actions/upload-artifact@v3
        with:
          name: built-image
          path: ./mdp-classwork-1_image.tar

  Push-image:
    runs-on: ubuntu-latest
    needs: Build-image
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: built-image
          path: .
      - name: Load Docker image from tar archive
        run: docker load -i ./mdp-classwork-1_image.tar
      - name: Authenticate into DockerHub
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u syndamia -p "$DOCKERHUB_PASSWORD"
      - name: Tag Docker image
        run: docker tag syndamia/mdp-classwork-1:latest syndamia/mdp-classwork-1:latest
      - name: Push Docker image
        run: docker push syndamia/mdp-classwork-1:latest
